// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiP08zsZwIl99d7NP9_9s0eTM36YW0Vxo',
    appId: '1:837395323823:web:5f699e5fd2b82c1928ed5a',
    messagingSenderId: '837395323823',
    projectId: 'padel-app-54f20',
    authDomain: 'padel-app-54f20.firebaseapp.com',
    storageBucket: 'padel-app-54f20.appspot.com',
    measurementId: 'G-KFEJPK0VNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmaf3BAbBuWn5v3KqvBoiRSfYO-Q4ddMc',
    appId: '1:837395323823:android:123a2c1d1f8f8be228ed5a',
    messagingSenderId: '837395323823',
    projectId: 'padel-app-54f20',
    storageBucket: 'padel-app-54f20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_evwa39U9f4GBvSyF1uIwEgIRerjklrc',
    appId: '1:837395323823:ios:e215efc7ce3aee7628ed5a',
    messagingSenderId: '837395323823',
    projectId: 'padel-app-54f20',
    storageBucket: 'padel-app-54f20.appspot.com',
    iosBundleId: 'com.example.padelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_evwa39U9f4GBvSyF1uIwEgIRerjklrc',
    appId: '1:837395323823:ios:15a570f3426bb97128ed5a',
    messagingSenderId: '837395323823',
    projectId: 'padel-app-54f20',
    storageBucket: 'padel-app-54f20.appspot.com',
    iosBundleId: 'com.example.padelApp.RunnerTests',
  );
}
